# Generated by Django 5.2.17 on 2026-09-27 23:23

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthorPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("author_reference", models.UUIDField(unique=True)),
                ("sha256", models.CharField(max_length=64)),
                ("image", models.ImageField(upload_to="publibot/autores/")),
                (
                    "received_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "foto de autor",
                "verbose_name_plural": "fotos de autor",
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="Conversion",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("day", models.DateField(db_index=True)),
                ("kind", models.CharField(blank=True, max_length=40)),
                ("via_cta", models.BooleanField(default=False)),
                ("first_channel", models.CharField(blank=True, max_length=10)),
                ("last_channel", models.CharField(blank=True, max_length=10)),
                ("journey", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("idempotency_key", models.UUIDField(unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("article", "Artigo"), ("qa", "Resposta")],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=300)),
                ("slug", models.SlugField(blank=True, max_length=300)),
                ("html_content", models.TextField()),
                ("excerpt", models.TextField(blank=True)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                ("focus_keyword", models.CharField(blank=True, max_length=120)),
                ("language", models.CharField(default="pt-br", max_length=10)),
                ("author_name", models.CharField(blank=True, max_length=150)),
                ("author_credentials", models.CharField(blank=True, max_length=200)),
                (
                    "author_reference",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("reviewed_by", models.CharField(blank=True, max_length=150)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("content_disclosure", models.TextField(blank=True)),
                ("canonical_source", models.URLField(blank=True, max_length=500)),
                ("cover_image_url", models.URLField(blank=True, max_length=500)),
                ("cover_image_alt", models.CharField(blank=True, max_length=300)),
                ("faq", models.JSONField(blank=True, default=list)),
                ("call_to_action", models.CharField(default="end", max_length=8)),
                ("related_articles", models.JSONField(blank=True, default=list)),
                (
                    "question_id",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("post_status", models.CharField(default="published", max_length=20)),
                ("publish_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("last_update_key", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "publicacao do PubliBot",
                "verbose_name_plural": "publicacoes do PubliBot",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UsedNonce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nonce", models.CharField(max_length=128, unique=True)),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VisitorQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_text", models.TextField(max_length=500)),
                ("author_name", models.CharField(blank=True, max_length=150)),
                ("consent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "submitted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "pergunta de visitante",
                "verbose_name_plural": "perguntas de visitantes",
                "ordering": ["submitted_at"],
                "indexes": [
                    models.Index(
                        fields=["acknowledged_at", "answered_at"],
                        name="publibot_co_acknowl_188fdf_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField()),
                ("views", models.PositiveIntegerField(default=0)),
                ("engaged_views", models.PositiveIntegerField(default=0)),
                ("engaged_seconds", models.PositiveIntegerField(default=0)),
                ("read_to_end", models.PositiveIntegerField(default=0)),
                ("cta_views", models.PositiveIntegerField(default=0)),
                ("cta_clicks", models.PositiveIntegerField(default=0)),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="publibot_core.publication",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("publication", "day"), name="publibot_leitura_do_dia"
                    )
                ],
            },
        ),
    ]
