# Generated by Django 5.2.17 on 2026-09-28 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publibot_core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="cover_image",
            field=models.ImageField(blank=True, upload_to="publibot/capas/"),
        ),
        migrations.AddField(
            model_name="publication",
            name="cover_image_sha256",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
