# Generated by Django 5.2.17 on 2026-10-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publibot_core", "0002_capa_no_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="call_to_action_copy",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
